/*
 * CustomUserStruct.h
 *
 *  Created on: Feb 10, 2020
 *      Author: pony
 */

#ifndef HEADER_CUSTOMUSERSTRUCT_H_
#define HEADER_CUSTOMUSERSTRUCT_H_

enum MessageType {

	MARKET_FRONT_CONNECTED = 0,
	MARKET_FRONT_LOGIN,
	MARKET_FRONT_LOGOUT,
	RSP_SUB_MARKETDATA,
	RTN_DEPTH_MARKETDATA,

	TRADER_FRONT_CONNECTED,
	RSP_AUTHENTICATE,
	TRADER_FRONT_LOGIN,
	TRADER_FRONT_LOGOUT,
	RSP_SETTLEMENT_INFO_CONFIRM,
	RSP_QRY_INSTRUMENT,
	RSP_QRY_TRADING_ACCOUNT,
	RSP_QRY_INVESTOR_POSITION,
	RSP_ORDER_INSERT,
	RSP_ORDER_ACTION,
	RTN_ORDER,
	RTN_TRADE,
};

struct Message{
	MessageType msg_type;
	void *data;
};


#endif /* HEADER_CUSTOMUSERSTRUCT_H_ */
